apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-connect
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-connect
  template:
    metadata:
      labels:
        app: debezium-connect
    spec:
      containers:
        - name: connect
          image: debezium/connect:2.6
          # imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: GROUP_ID
              value: "debezium"
            - name: CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: STATUS_STORAGE_TOPIC
              value: "connect-status"
---
apiVersion: v1
kind: Service
metadata:
  name: debezium-connect
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  selector:
    app: debezium-connect
