replicaCount: 1

image:
  repository: debezium/connect
  tag: 2.7.1.Final

config:
  BOOTSTRAP_SERVERS: "kafka:9092"
  GROUP_ID: "1"
  CONFIG_STORAGE_TOPIC: "connect-configs"
  OFFSET_STORAGE_TOPIC: "connect-offsets"
  STATUS_STORAGE_TOPIC: "connect-status"
  KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  KEY_CONVERTER_SCHEMAS_ENABLE: "false"
  VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

service:
  type: NodePort
  nodePort: 30803

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"
