cluster:
  enabled: false

usePassword: false

master:
  persistence:
    enabled: false
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
