global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']


  - job_name: "node-services"
    static_configs:
      - targets:
          - "auth:4000"
          - "catalog:4001"
          - "orders:4002"
          - "cart:4003"
          - "payments:4004"
          - "notification:4005"
