name: "Reusable CI for Service"

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      path:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Debug: pwd & service folder
      - name: Debug service folder
        run: |
          echo "Current working directory: $(pwd)"
          echo "Listing files in ${{ inputs.path }}:"
          ls -la ${{ inputs.path }}

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build & push with multiple tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.path }}
          file: ${{ inputs.path }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mv100-${{ inputs.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mv100-${{ inputs.service }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mv100-${{ inputs.service }}:${{ github.ref_name }}
